spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lloyd
    password: Qly.shuai666
    url: jdbc:mysql://120.46.196.129:3306/menu?characterEncoding=utf-8&useSSL=false
  redis:
    host: 120.46.196.129
    port: 6379
    password: Qly.shuai666
wx:
  miniapp:
    appid: your_appid_here
    secret: your_secret_here
#  rabbitmq:
#    addresses: 120.46.196.129
#    port: 5672
#    username: guest
#    password: guest
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024
    compression-level: 6

app:
  upload:
    path: d:/project/menu/uploads
