spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lloyd
    password: Qly.shuai666
    url: jdbc:mysql://106.52.97.177:3306/menu?characterEncoding=utf-8&useSSL=false
  data.redis:
    host: 106.52.97.177
    port: 6379
    password: Qly.shuai666
  rabbitmq:
   addresses: 106.52.97.177
   port: 5672
   username: admin
   password: admin
wx:
  miniapp:
    appid: your_appid_here
    secret: your_secret_here
jwt:
  secret: 012345678901234567890123456789012345678901234567890123456789
  expiration: 86400000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024
    compression-level: 6

app:
  upload:
    path: d:/project/menu/uploads
